name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ ! -d "cloud-task-engine" ]; then
            git clone https://github.com/${{ github.repository }}.git cloud-task-engine
          fi
          cd cloud-task-engine
          git pull origin main
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" > .env
          echo "SQS_QUEUE_URL=${{ secrets.SQS_QUEUE_URL }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          docker-compose down
          docker-compose up -d --build
